account/urls.py
from django.conf.urls import url 
from django.contrib.auth import views as auth_views
from account.views import signup

urlpatterns=[
    url(r'signup/$',signup,name='signup'),
    url(r'login/$',auth_views.login,{'template_name':'login.html'},name='login'),
    url(r'logout/$',auth_views.logout,{'next_page':'home'},name='logout'),
]

projectone/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from todo.views import home,todolist

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',home,name="home"),
    url(r'^todos/$',todolist,name="todolist"),
    url(r'^todos/',include('todo.urls',namespace="todo")),
    url(r'^accounts/',include('account.urls')),
]

todo/urls.py
from django.conf.urls import url
from todo.views import todoadd,todolist,about,contact,todoedit,tododelete

urlpatterns=[
    url(r'^$',todolist,name='todolist'),
    url(r'^add/$',todoadd,name='todoadd'),
    url(r'^contact/$',contact,name='contact'),
    url(r'^about/$',about,name='about'),
    url(r'^edit/(?P<pk>\d+)/$',todoedit,name='todoedit'),
    url(r'^delete/(?P<pk>\d+)/$',tododelete,name='tododelete'),
       
]

account/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    title=models.CharField(max_length=255)
    description=models.TextField(max_length=255)
    name=models.CharField(max_length=200)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

class Contact(models.Model):
    name=models.CharField(max_length=255)
    email=models.CharField(max_length=200)
    mobileno=models.CharField(max_length=200)
    message=models.CharField(max_length=200)

todo/forms.py
from django import forms
from todo.models import Contact, Todo


class TodoForm(forms.ModelForm):
    class Meta:
        model=Todo
        fields={"title","description","name"}

class ContactForm(forms.ModelForm):
    class Meta:
        model=Contact
        fields={"name","email","mobileno","message"}

account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login

# Create your views here.
def signup(request):
    signupform=UserCreationForm(request.POST or None)
    if signupform.is_valid():
        signupform.save()
        username=signupform.cleaned_data.get("username")
        raw_password=signupform.cleaned_data.get("password1")

        user=authenticate(username=username,password=raw_password)
        login(request,user)
        return redirect("todolist")
    return render(request,'signup.html',{'form':signupform})

            

todo/views.py
from django.shortcuts import render,redirect,get_object_or_404
from todo.models import Todo
from todo.forms import TodoForm
from todo.forms import ContactForm 
from todo.models import Contact
from django.contrib.auth.decorators import login_required



# Create your views here.
def home(request):
    return render(request,'home.html')
@login_required
def about(request):
    return render(request,'about.html')
@login_required
def contact(request):
    contactform= ContactForm(request.POST or None)
    if contactform.is_valid():
        contactform.save()
        return redirect('home')
    return render(request,'contact.html',{'form':contactform})
    

@login_required
#add the feedbacks
def todoadd(request):
    todoform= TodoForm(request.POST or None)
    if todoform.is_valid():
        todoform.save()
        return redirect('todolist')
    return render(request,'todoadd.html',{'form':todoform})

@login_required
#reading all the feedbacks
def todolist(request):
    allfeedback=Todo.objects.all()
    return render(request,'todolist.html',{'todos':allfeedback})

@login_required
def todoedit(request,pk):
    todo = get_object_or_404(Todo,pk=pk)
    todoform=TodoForm(request.POST or None, instance=todo)
    if todoform.is_valid():
        todoform.save()
        return redirect ('todolist')
    return render(request,'todoadd.html',{'form':todoform})

@login_required
def tododelete(request,pk):
    todo=get_object_or_404(Todo,pk=pk)
    if request.method=='POST':
        todo.delete()
        return redirect('todolist')
    return render(request,'tododelete.html',{'todo':todo})

templates/about.html
{% extends 'base.html' %}


{% block content %}
<head>
    <style>
        h1{
            font-family: 'Courier New', Courier, monospace;
            font-size: 35px;
            font-weight: bold;
            color: brown;
            margin: 20px;
         
        }
        p{
            width: 65%;
            height: 100%;
            text-align: justify;
            margin: 20px;
        }
        .img{
            float: right;
          width: 30%;
          height: 500px;
          margin-top: -700px;
        }
        
    </style>
</head>
<h1> About Us</h1>
<p>LIVEWIRE – A Division of CADD Centre Training Services Pvt Ltd, is an approved Skill Development Partner of National Skill Development Corporation (NSDC). LIVEWIRE promotes a unique combination of technologies that are specific to IT, Computer science, Electronics & Electrical departments. We deal with Emerging technologies like Data science, Machine Learning, IoT, Artificial Intelligence, Blockchain, Full Stack Developer, Cyber security, Automotive Embedded system and many more. LIVEWIRE is present in more than 100 locations in India and over 7 countries.
<br><br>
LIVEWIRE credential includes its affiliation like NSDC, STED Council, MSME, ISO (9001:2015 & 29990:2010), NIELIT, AXELOS, Oracle, CompTIA, Blockchain Council etc. LIVEWIRE works closely with more than 1000 colleges in India as a technology partner in equipping students beyond their academics and also with few corporate clients for their training requirements.
<br><br>
The curricula are prepared with inputs from the product companies and industry experts. The training is offered by instructors who are trained by the Product developers and industry experts. Our training centre boast of high-end hardware and sophisticated technology labs that are modelled on real world R&D units of industries.
</p>
<img class="img" src="https://www.livewireindia.com/images/loan.jpg" alt="">
{% endblock %}

templates/base.html
<html>

<head>
    <link rel="icon" href="https://www.livewireindia.com/favicon.ico">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
</head>

    
{% include 'navbar.html' %}
{% block content %}

    

 

    
  

{% endblock %}
{%include 'footer.html'%}




</html>

templates/contact.html
{% extends 'base.html' %}



{% block content %}
<head>
    <style>
    .bg{
                background-color:coral;
            }
   .contact{
        text-align: center;
        background-color: cornsilk;
        color: brown;
        font-size: 20px;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
        border:3px solid brown;

      }
    .map{
      width: 50%;
      }
    form{
          float: right;
          width: 50%;
          height: 600px;
          margin-top: -600px;
          text-align: center;
          background-color: cornsilk;
         
        }
        h1{
          text-align:"center";
          font-size: 30px; 
          font-family: Georgia, 'Times New Roman', Times, serif;
          color: brown; 
        }
        h2{
          text-align:"center";
          font-size:30px; 
          font-family: Georgia, 'Times New Roman', Times, serif;
          color: brown;
        }
        input{
          width: 300px;
          height: 50px;
          text-align: center;
          border-radius: 20px;
          color: brown;
        }
        button{
          background-color: crimson;
          color: white;
          border-radius: 20px;
          width: 200px;
          height: 50px;

        }
        button:hover{
          background-color: darkblue;
        }
    </style>
</head>

<div class="contact">
    <h1>Reach Us</h1>
    <p> Office No:-206 Kyro Building Bhawarkua Square Indore, MadhyaPradesh</p>
    <p>Pin Code:-452001</p>
    <p>Contact:<i class="fa fa-phone"></i>+91 6262474111</p>
    <p>Email:<i class="fa fa-envelope"></i>-livewireindore3@gmail.com</p>
   </div>
   <hr>
   <div class="map">
    <div style="width: 100%"><iframe width="100%" height="600" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=bhawarkua%20square%20452001+(Livewire%20Indore)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"><a href="https://www.gps.ie/sport-gps/">swimming watch</a></iframe></div>
   </div>
   <div>
     <form method="POST">
     <h2>Enquirey Form</h2><br>
     {% csrf_token %}
     {{form.as_p}}
    <button type="submit">Enquire Now </button>
    </form>
    </div>







    
    
    


{% endblock %}

templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Livewire</title>
    <style>
        .ft{
            height: 60px;
            background-color: rgb(247, 215, 176);
           
                  
            }
        .ft1{
            margin-left: 630px;
            color: brown;
            font-size: 20px;
            font-family: 'Courier New', Courier, monospace;
           
            }
      </style>
</head>
<body>
    <nav class="ft">
        <p class="ft1">Contact Us:-<i class="fa fa-phone"></i>
        +91 6262474111
        <i class="fa fa-envelope"></i>livewireindore3@gmail.com</p>
      </nav>
    
</body>
</html>

templates/home.html
{% extends 'base.html' %}



{% block content %}
<head>
<style>
  h1{
    text-align: center;
    font-family: 'Times New Roman', Times, serif;
    font-size: 40px;
    font-weight: bold;
    color: blue;
  }
  .img{
    margin: 40px;
  }
  h3{
    text-align: center;
    font-size: 30px;
    font-family: 'Times New Roman', Times, serif;
    font-weight: bold;
    color: blue;
  }
  p{
    text-align: center;
    font-family: 'Times New Roman', Times, serif;
    font-size: 15px;
    color: grey;
  }

</style>
</head>

<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img height="90%" width="100%" src="https://www.livewireindia.com/images/banner/banner_v2/home/L&T-livewire.jpg" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img height="90%" width="100%" src="https://www.livewireindia.com/images/course/partners.png" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img height="90%" width="100%" src="https://www.livewireindia.com/images/content/bg/01.jpg" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <br>

<h1>TRENDING COURSES</h1>
  <div class="row">
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img class="img" height="250px" width="350px" src="https://www.livewireindia.com/images/content/portfolios/square/half-2.jpg" alt="...">
        <div class="caption">
          <h3>Data Science</h3>
          <p>Treanding Technology</p>
          <p><a href="#" class="btn btn-primary" role="button">Enquire Now</a></p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img class="img" height="250px" width="350px" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTN_nt9qFkrQ5xriXLaWDqV8eDiICWEK8sYsg&usqp=CAU" alt="...">
        <div class="caption">
          <h3>Python</h3>
          <p>Treanding Technology</p>
          <p><a href="#" class="btn btn-primary" role="button">Enquire Now</a></p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img class="img" height="250px" width="350px" src="https://www.livewireindia.com/images/content/portfolios/square/blockchain.jpg" alt="...">
        <div class="caption">
          <h3>Block Chain</h3>
          <p>Treanding Technology</p>
          <p><a href="#" class="btn btn-primary" role="button">Enquire Now</a></p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img class="img" height="250px" width="350px" src="https://imageio.forbes.com/specials-images/dam/imageserve/966248982/960x0.jpg?fit=bounds&format=jpg&width=960" alt="...">
        <div class="caption">
          <h3>Machine Learning</h3>
          <p>Treanding Technology</p>
          <p><a href="#" class="btn btn-primary" role="button">Enquire Now</a></p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img class="img" height="250px" width="350px" src="https://www.livewireindia.com/images/content/portfolios/thumb/django.jpg" alt="...">
        <div class="caption">
          <h3>Django</h3>
          <p>Treanding Technology</p>
          <p><a href="#" class="btn btn-primary" role="button">Enquire Now</a></p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img class="img" height="250px" width="350px" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREhukwfJEjS8LCc9edhWzF9IYQbBQBJNKrDQVSDpIGsfjPX5nyO_i5okJsWK8AIukIYG4&usqp=CAU" alt="...">
        <div class="caption">
          <h3>Artificial Intelligence</h3>
          <p>Treanding Technology</p>
          <p><a href="#" class="btn btn-primary" role="button">Enquire Now</a></p>
        </div>
      </div>
    </div>
  </div>

  
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
<head>
    <style>
        form{
            margin-left: 500px;
            color:blue
        }
        h1{
            color:orange;
        }

    </style>
</head>
<form method="post">
    <h1>Login Here</h1>

    {%csrf_token%} 
    {{form.as_p}}
    <button style="color:white;background-color:blue;font-size:20px;border-radius:10px;margin-left:100px;" type="submit" name="login">Login</button>

</form>
{% endblock %}

templates/logout.html
{% extends 'base.html' %}

{% block content %}

    <h1>You Have Successfully Logged Out</h1>

    
{% endblock %}

templates/navbar.html
<head>
    <style>
        .nv{
            background-color: salmon;
        }
    </style>
</head>
<nav class="navbar navbar-red nv">
    <img height="60px" width="200px" src="https://support.livewireindia.com/tmp/images/live_wire_logo.jpg" alt="logo">
    
    <a class="nav-link" style="color:white;font-weight: bold; font-family: 'Courier New', Courier, monospace;font-size: 20px;" href="http://127.0.0.1:8000/">Home</a>
    <a class="nav-link" style="color:white;font-weight: bold; font-family: 'Courier New', Courier, monospace;font-size: 20px;" href="http://127.0.0.1:8000/todos/contact">Contact</a>
    <a class="nav-link" style="color:white;font-weight: bold; font-family: 'Courier New', Courier, monospace;font-size: 20px;" href="http://127.0.0.1:8000/todos/about">About</a>
    <a class="nav-link" style="color:white;font-weight: bold; font-family: 'Courier New', Courier, monospace;font-size: 20px;" href="http://127.0.0.1:8000/todos">All Feedbacks</a>
    <a class="nav-link" style="color:white;font-weight: bold; font-family: 'Courier New', Courier, monospace;font-size: 20px;" href="http://127.0.0.1:8000/todos/add">Add Your Own Feedback</a>
    <a class="nav-link" style="color:white;font-weight: bold; font-family: 'Courier New', Courier, monospace;font-size: 20px;" href="http://127.0.0.1:8000/accounts/signup">SignUp</a>
    <a class="nav-link" style="color:white;font-weight: bold; font-family: 'Courier New', Courier, monospace;font-size: 20px;" href="http://127.0.0.1:8000/accounts/login">SignIn</a>
    <div>
        {%if user.is_authenticated%} 
        <p>Hi,{{user.username}}!!Welcome <a href="{%url 'logout' %}">Logout</a></p>
        {%endif%}
    </div>


</nav>

templates/signup.html
{% extends 'base.html' %}

{% block content %}
<head>
    <style>
        form{
            margin-left: 400px;
            color:blue
        }
        h1{
            color:orange;
        }

    </style>
</head>
<form method="post">
    <h1>Register Yourself</h1>

    {%csrf_token%} 
    {{form.as_p}}
    <button style="color:white;background-color:blue;font-size:20px;border-radius:10px;margin-left:200px;" type="submit" name="signup">Signup</button>

</form>
{% endblock %}

templates/todoadd.html
{% extends 'base.html' %}



{% block content %}
<head>
    <style>
        form{
            background-color: darkslategrey;
            color:bisque;
            font-size: 20px;
            font-weight: bold;
            font-family: 'Courier New', Courier, monospace;
            height: 80%;
            }
            
        input{
                color: tomato;
                border: 2px solid white;
                background-color:white;
                border-radius: 10px;
                margin-left: 20px;
            }
        button{
                background-color: bisque;
                color: blue;
                font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
                font-size: 15px;
                width: 100px;
                height: 50px;
                border-radius: 30px;
            }
        button:hover{
                background-color: cyan;
            }
        .nt{
            color:bisque;
            font-family: 'Times New Roman', Times, serif;
            font-size: 20px;
            background-color: darkslategrey;
        }
        
    </style>
</head>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button value="savetodo">Submit</button>

</form>
<p class="nt">
Note:- Here You Can Add Your Own Feedback It Will Valueable For Us!
</p>





{% endblock %}

templates/tododelete.html
{% extends 'base.html' %}



{% block content %}
<head>
    <style>
        form{
            margin-left: 600px;
            color: blue;
            font-size: 20px;
        }
        button{
            background-color: blue;
            color: white;
            font-size: 20px;
        }

    </style>
</head>
<form method="post">
    {%csrf_token%} 
    <p>Are You Sure ?</p>
    <p>Yes I want to delete"{{todo.title}}"</p>
    <button style="border-radius: 20px;" type="submit" name="tododelete">Delete</button>
    
</form>
<a href="http://127.0.0.1:8000/todos/">Go Back</a>
{% endblock %}

templates/todolist.html
{% extends 'base.html'%}
{%block content%}


<style>
	table{
		width: 100%;
	}
th,td,tr{
border:2px solid crimson;
height: 50px;
width: 200px;
text-align: center;}

h3{
color:crimson}
th{
color:crimson}
button{
	border: none;
	background-color: crimson;
	color: white;
	border-radius: 20px;
}
a{
	text-decoration: none;
}
</style>
<h3 align="center">All are Your Valueable Feedbacks Here</h3>
<table align="center" id="table">

  <thead>
     <tr>
        <th>Title</th>
		<th>Description</th>
		<th>Name</th>
		<th>Created at</th>
		<th>Updated at</th>
		<th>Update/Delete</th>
     </tr>	 
  
  </thead>
  
  <tbody>
  
  {%for todo in todos%}
     <tr>
	   <td>{{todo.title}}</td>
	   <td>{{todo.description}}</td>
	   <td>{{todo.name}}</td>
	   <td>{{todo.created_at}}</td>
	   <td>{{todo.updated_at}}</td>
	   <td>
	    <a href="{%url 'todo:todoedit' todo.id%}">
		<button>Update</button></a>
		
		<a href="{%url 'todo:tododelete' todo.id%}">
		<button >Delete</button></a>
	   
	   </td>
	 
	 
	 </tr>
  {%endfor%}
  </tbody>

</table>
<br><br>
<button><a id="downloadLink" onclick="exportF(this)">Download into Excel</a></button>


<script>
function exportF(elem) {
  var table = document.getElementById("table");
  var html = table.outerHTML;
  var url = 'data:application/vnd.ms-excel,' + escape(html); // Set your html table into url 
  elem.setAttribute("href", url);
  elem.setAttribute("download", "export.xls"); // Choose the file name
  return false;
}

</script>

{%endblock%}